name: weather_app
description: A weather forecast app

dependencies:
  flutter:
    sdk: flutter
  device_preview: ^1.2.0
  geolocator: ^10.0.1
  weather: ^3.1.1
  intl: ^0.19.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: "^3.4.0"

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/
